# Perceptron 

In [10]:
from random import choice
import numpy as np

In [131]:
class Perceptron: 
    
    def __init__(self):
        pass
       
    def train(self, X , Y):
        X = np.asarray(X)
        Y = np.asarray(Y)
        
        (n,m) = X.shape
        X = np.append(X, np.ones((n,1)),1)
        w = np.zeros(m+1)
        
        erro = 1
        maxiter = 100
        ciclo = 1
        while erro > 0 and ciclo < maxiter:
            erro = 0
            for y,x in zip(Y,X):
                dot = np.dot(w,x)
                if(dot <= 0):
                    yp = 0
                else:
                    yp = 1
                print("%a inner %a dot %i =>  %i = %i "%(w,x,dot,yp, y))
                if yp != y:
                    w = w + 1*(yp-y)*x
                    erro+=1
            ciclo+=1
            print(ciclo)
        
        return Predictor(w)
    

In [132]:
class Predictor:
    
    def __init__(self, w):
        self.w = w
        pass
    
    def predict(self,X):   
        X = np.asarray(X)
        (n,m) = X.shape
        X = np.append(X, np.ones((n,1)),1)
        
        print(self.w)
        y=[]
        
        y = np.dot(X, self.w)
        
        return y

In [133]:
x = [[0,0],
    [0,1],
    [1,0],
    [1,1]]

y = [0,1,1,1]

p = Perceptron();
preditor = p.train(x,y)
print(preditor.predict(x))


array([ 0.,  0.,  0.]) inner array([ 0.,  0.,  1.]) dot 0 =>  0 = 0 
array([ 0.,  0.,  0.]) inner array([ 0.,  1.,  1.]) dot 0 =>  0 = 1 
array([ 0., -1., -1.]) inner array([ 1.,  0.,  1.]) dot -1 =>  0 = 1 
array([-1., -1., -2.]) inner array([ 1.,  1.,  1.]) dot -4 =>  0 = 1 
2
array([-2., -2., -3.]) inner array([ 0.,  0.,  1.]) dot -3 =>  0 = 0 
array([-2., -2., -3.]) inner array([ 0.,  1.,  1.]) dot -5 =>  0 = 1 
array([-2., -3., -4.]) inner array([ 1.,  0.,  1.]) dot -6 =>  0 = 1 
array([-3., -3., -5.]) inner array([ 1.,  1.,  1.]) dot -11 =>  0 = 1 
3
array([-4., -4., -6.]) inner array([ 0.,  0.,  1.]) dot -6 =>  0 = 0 
array([-4., -4., -6.]) inner array([ 0.,  1.,  1.]) dot -10 =>  0 = 1 
array([-4., -5., -7.]) inner array([ 1.,  0.,  1.]) dot -11 =>  0 = 1 
array([-5., -5., -8.]) inner array([ 1.,  1.,  1.]) dot -18 =>  0 = 1 
4
array([-6., -6., -9.]) inner array([ 0.,  0.,  1.]) dot -9 =>  0 = 0 
array([-6., -6., -9.]) inner array([ 0.,  1.,  1.]) dot -15 =>  0 = 1 
array([ -6.

In [120]:
w = [0,-1,-1]
x = [1,0,1]
np.dot(w,x)

-1